### ISSUE TITLE
Pip import error

### ISSUE THREAD

**Issue by royal78** [BaraniARR/anikimiapi#1]
Importing module failed and given the error :
`No module named anikimiapi`
Try to publish an update to pypi 

Or 

have a `__init__.py?`
Check it and try  to correct it
To make import walk through your directories every directory must have a `__init__.py` file

**Comment by BaraniARR** [comment]
![image](https://user-images.githubusercontent.com/76671069/128460206-d975312f-8cac-4406-a108-d7aad48a6c98.png)

It's working totally fine. Please try it in virtualenv...
