### ISSUE TITLE
[Feature] [TOKEN extraction method] #Add to README.md

### ISSUE THREAD

**Issue by heartlog** [BaraniARR/anikimiapi#6]
## description
it's kinda pain to extract the token using pc...
Its following methods which i know about token and cookies data extraction
##  Methods
**1. Method - using android debug mode**
Its kinda pain but you can see it [how-do-i-extract-and-view-cookies-from-android-chrome](https://stackoverflow.com/questions/36101403/how-do-i-extract-and-view-cookies-from-android-chrome) 

**2. Method - using third party android browser**
Its easy and convenient even noob in coding can also do it. [App in Play store](https://play.google.com/store/apps/details?id=com.webviewtest.app)

**3. Method - using `eruda` Dev consule for all browsers.**
Its easy You can find repo Here 
__Just copy code ↓__
>`javascript:(function () {     var script =  document.createElement('script');    script.src="//cdn.jsdelivr.net/npm/eruda";     document.body.appendChild(script);    script.onload = function () {         eruda.init()     } })();`

**Bookmark it and name it as** `Inspect element`
**Then you can use it in any browser..**

## YOU CAN REFER [STACKOVERFLOW](https://stackoverflow.com/questions/36101403/how-do-i-extract-and-view-cookies-from-android-chrome) for this.

Keep going on!!
 [I](https://t.me/diablo_13N) like your work 🍭

**Comment by BaraniARR** [comment]
But, is there a need to get cookies from an android browser? you  are absolutely going to use PC for programming. Anyway, I'll research and commit your changes.

**Comment by heartlog** [comment]
> But, is there a need to get cookies from an android browser? you are absolutely going to use PC for programming. Anyway, I'll research and commit your changes.

its true i also use pc for that 😅

But the more options is good no ?
since, i suggested that methods which i use when i surf web on the sparetime.
Anyway keep going
**And can you make api or just a script for animephae also ?**
I made it but for some anime it extact link and for some links its gives error 🙄😑.
You can dm me on [Telegram](t.me/diablo_13N)
